//! Golden test vectors for the wire format: `docs/design/wbf-vectors.json`.
//!
//! The file is the executable half of the specification. It is generated by
//! this module (run the `regenerate` test with `WBF_VECTORS_WRITE=1`), never
//! written by hand, and every implementation of the format, this server and
//! any client in any language, tests itself against the same file. A change
//! to the format that is not reflected in the vectors fails here; a client
//! that copies the file and falls behind fails there.
//!
//! Byte strings are lowercase hex. `meta` is given both as hex and, when it is
//! UTF-8, as text, so a reader can see what it is.

use serde_json::{Value, json};

use super::{
	ENCRYPTED_FILE_INFO_LEN, EncryptedFileInfo, Flags, Kind, PackBuilder, PackError, decode,
};

/// Where the vectors live, relative to this file.
const VECTORS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../docs/design/wbf-vectors.json");

/// The vectors as built into this binary; the file must match them.
const VECTORS: &str = include_str!("../../../docs/design/wbf-vectors.json");

fn hex(bytes: &[u8]) -> String { bytes.iter().map(|b| format!("{b:02x}")).collect() }

fn unhex(text: &str) -> Vec<u8> {
	(0..text.len())
		.step_by(2)
		.map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("hex digit pair"))
		.collect()
}

/// Every vector, computed from the implementation. Regenerating the file is
/// serializing this; checking the file is comparing it to this.
fn current() -> Value {
	let pack = |name: &str, kind: Kind, subtype: u8, flags: Flags, id: u64, seq: u32, meta: &[u8], data: &[u8]| {
		let bytes = PackBuilder::new(kind, subtype, flags, id, seq)
			.meta(meta)
			.expect("meta fits")
			.data(data)
			.expect("data fits")
			.finish();
		json!({
			"name": name,
			"kind": kind as u8,
			"subtype": subtype,
			"flags": flags.0,
			"id": id,
			"seq": seq,
			"meta_hex": hex(meta),
			"meta_text": std::str::from_utf8(meta).ok(),
			"data_hex": hex(data),
			"bytes_hex": hex(&bytes),
		})
	};

	let info = |file_size: u64, chunk_size: u32, chunk_count: u32| {
		let value = EncryptedFileInfo { file_size, chunk_size, chunk_count };
		json!({
			"file_size": file_size,
			"chunk_size": chunk_size,
			"chunk_count": chunk_count,
			"bytes_hex": hex(&value.encode()),
		})
	};

	let create_meta = EncryptedFileInfo { file_size: 132056, chunk_size: 65536, chunk_count: 3 }.encode();
	let good = pack("chunk", Kind::Upload, 0x02, Flags::default(), 0x1122_3344_5566_7788, 0, b"", b"\xde\xad\xbe\xef\x01");

	// Damaged copies of `good`, one field at a time.
	let good_bytes = unhex(good["bytes_hex"].as_str().expect("hex"));
	let damaged = |name: &str, mutate: &dyn Fn(&mut Vec<u8>), error: &str| {
		let mut bytes = good_bytes.clone();
		mutate(&mut bytes);
		json!({ "name": name, "bytes_hex": hex(&bytes), "error": error })
	};

	json!({
		"format_version": 1,
		"about": "Golden vectors for the wbf pack and EncryptedFileInfo. Generated by src/core/wbf/vectors.rs; do not edit by hand.",
		"crc32c": [
			{ "input_hex": hex(b""), "crc": crc32c::crc32c(b"") },
			{ "input_hex": hex(b"123456789"), "crc": crc32c::crc32c(b"123456789") },
			{ "input_hex": hex(b"\xde\xad\xbe\xef\x01"), "crc": crc32c::crc32c(b"\xde\xad\xbe\xef\x01") },
		],
		"encrypted_file_info": [
			info(132056, 65536, 3),
			info(65550, 16384, 5),
			info(0, 16384, 0),
			info(u64::MAX, u32::MAX, u32::MAX),
		],
		"packs": [
			pack("hello", Kind::Control, 0x01, Flags::default(), 0, 1, br#"{"protocol":1,"client":"e2e","features":[]}"#, b""),
			pack("ping", Kind::Control, 0x04, Flags::default(), 0, 2, br#"{"nonce":42}"#, b""),
			pack("create", Kind::Upload, 0x01, Flags::default(), 0, 3, &create_meta, b"<ciphertext of the file description>"),
			good,
			pack("chunk_last", Kind::Upload, 0x02, Flags::IS_LAST, 0x1122_3344_5566_7788, 2, b"", b"\xde\xad\xbe\xef\x01"),
			pack("status", Kind::Upload, 0x03, Flags::default(), 0x1122_3344_5566_7788, 4, b"", b""),
			pack("seal", Kind::Upload, 0x04, Flags::default(), 0x1122_3344_5566_7788, 5, b"", b""),
			pack("abort", Kind::Upload, 0x05, Flags::default(), 0x1122_3344_5566_7788, 6, b"", b""),
			pack("info", Kind::Download, 0x01, Flags::default(), 0, 7, br#"{"mxc":"mxc://localhost/1122334455667788"}"#, b""),
			pack("read_by_pos", Kind::Download, 0x02, Flags::default(), 0, 8, br#"{"mxc":"mxc://localhost/1122334455667788","pos":131079}"#, b""),
			pack("read_by_chunk", Kind::Download, 0x02, Flags::default(), 0, 9, br#"{"mxc":"mxc://localhost/1122334455667788","chunk":2}"#, b""),
			pack("ack_chunk", Kind::Control, 0x02, Flags::IS_RESPONSE, 0x1122_3344_5566_7788, 0, br#"{"received":1,"chunk_count":3,"total_len":65552,"finished":false,"truncated":false}"#, b""),
			pack("ack_read", Kind::Control, 0x02, Flags::IS_RESPONSE, 0, 8, br#"{"chunk":2,"pos":131072,"len":5,"chunk_size":65536,"chunk_count":3,"total_len":132104}"#, b"\xde\xad\xbe\xef\x01"),
			pack("error_out_of_order", Kind::Control, 0x03, Flags::IS_RESPONSE, 0x1122_3344_5566_7788, 2, br#"{"code":"OutOfOrder","expected_seq":1,"message":"expected chunk 1"}"#, b""),
			pack("empty", Kind::Control, 0x04, Flags::default(), 0, 0, b"", b""),
		],
		"rejected": [
			damaged("version_zero", &|b| b[0] = 0, "UnsupportedVersion"),
			damaged("unknown_kind", &|b| b[1] = 0x7f, "UnknownKind"),
			damaged("reserved_flag", &|b| b[3] = 0x80, "ReservedFlags"),
			damaged("header_bit_flipped", &|b| b[5] ^= 1, "MetaCrc"),
			damaged("data_bit_flipped", &|b| { let n = b.len(); b[n - 5] ^= 0xff; }, "DataCrc"),
			damaged("truncated", &|b| { b.pop(); }, "Truncated"),
			damaged("trailing_byte", &|b| b.push(0), "TrailingBytes"),
			damaged("too_short", &|b| b.truncate(31), "TooShort"),
			damaged("meta_len_past_end", &|b| { b[16..20].copy_from_slice(&u32::MAX.to_be_bytes()); }, "Truncated"),
		],
	})
}

fn error_name(error: PackError) -> &'static str {
	match error {
		| PackError::TooShort { .. } => "TooShort",
		| PackError::UnsupportedVersion(_) => "UnsupportedVersion",
		| PackError::UnknownKind(_) => "UnknownKind",
		| PackError::ReservedFlags(_) => "ReservedFlags",
		| PackError::Truncated { .. } => "Truncated",
		| PackError::TrailingBytes { .. } => "TrailingBytes",
		| PackError::MetaCrc { .. } => "MetaCrc",
		| PackError::DataCrc { .. } => "DataCrc",
		| _ => "Other",
	}
}

/// `WBF_VECTORS_WRITE=1 cargo test -p tuwunel_core wbf::vectors::regenerate`
/// rewrites the file from the implementation. Without the variable this
/// test only reports whether the file is current.
#[test]
fn regenerate() {
	let computed = current();
	let text = serde_json::to_string_pretty(&computed).expect("serializes");
	if std::env::var_os("WBF_VECTORS_WRITE").is_some() {
		std::fs::write(VECTORS_PATH, format!("{text}\n")).expect("vectors written");
	}
	let on_disk: Value = serde_json::from_str(VECTORS).expect("vectors file is JSON");
	assert_eq!(
		on_disk,
		computed,
		"docs/design/wbf-vectors.json is stale; regenerate it with WBF_VECTORS_WRITE=1"
	);
}

/// The file's packs decode to the fields it says, and re-encode to the bytes
/// it says. This is the test a client copies.
#[test]
fn packs_round_trip_against_the_file() {
	let vectors: Value = serde_json::from_str(VECTORS).expect("vectors file is JSON");
	for pack in vectors["packs"].as_array().expect("packs") {
		let name = pack["name"].as_str().expect("name");
		let mut bytes = unhex(pack["bytes_hex"].as_str().expect("bytes"));
		let view = decode(&mut bytes).unwrap_or_else(|e| panic!("{name}: {e:?}"));
		assert_eq!(view.header.kind as u8, pack["kind"].as_u64().expect("kind") as u8, "{name}: kind");
		assert_eq!(u64::from(view.header.subtype), pack["subtype"].as_u64().expect("subtype"), "{name}: subtype");
		assert_eq!(u64::from(view.header.flags.0), pack["flags"].as_u64().expect("flags"), "{name}: flags");
		assert_eq!(view.header.id, pack["id"].as_u64().expect("id"), "{name}: id");
		assert_eq!(u64::from(view.header.seq), pack["seq"].as_u64().expect("seq"), "{name}: seq");
		assert_eq!(hex(view.meta), pack["meta_hex"].as_str().expect("meta"), "{name}: meta");
		assert_eq!(hex(view.data), pack["data_hex"].as_str().expect("data"), "{name}: data");

		let rebuilt = PackBuilder::new(
			Kind::try_from(view.header.kind as u8).expect("kind"),
			view.header.subtype,
			view.header.flags,
			view.header.id,
			view.header.seq,
		)
		.meta(&unhex(pack["meta_hex"].as_str().expect("meta")))
		.expect("meta fits")
		.data(&unhex(pack["data_hex"].as_str().expect("data")))
		.expect("data fits")
		.finish();
		assert_eq!(hex(&rebuilt), pack["bytes_hex"].as_str().expect("bytes"), "{name}: re-encoded bytes");
	}
}

#[test]
fn rejected_packs_fail_the_way_the_file_says() {
	let vectors: Value = serde_json::from_str(VECTORS).expect("vectors file is JSON");
	for case in vectors["rejected"].as_array().expect("rejected") {
		let name = case["name"].as_str().expect("name");
		let mut bytes = unhex(case["bytes_hex"].as_str().expect("bytes"));
		let error = decode(&mut bytes).err().unwrap_or_else(|| panic!("{name}: decoded"));
		assert_eq!(error_name(error), case["error"].as_str().expect("error"), "{name}");
	}
}

#[test]
fn file_info_and_crc_match_the_file() {
	let vectors: Value = serde_json::from_str(VECTORS).expect("vectors file is JSON");
	for case in vectors["encrypted_file_info"].as_array().expect("file info") {
		let bytes = unhex(case["bytes_hex"].as_str().expect("bytes"));
		assert_eq!(bytes.len(), ENCRYPTED_FILE_INFO_LEN);
		let decoded = EncryptedFileInfo::decode(&bytes).expect("decodes");
		assert_eq!(decoded.file_size, case["file_size"].as_u64().expect("file_size"));
		assert_eq!(u64::from(decoded.chunk_size), case["chunk_size"].as_u64().expect("chunk_size"));
		assert_eq!(u64::from(decoded.chunk_count), case["chunk_count"].as_u64().expect("chunk_count"));
		assert_eq!(hex(&decoded.encode()), case["bytes_hex"].as_str().expect("bytes"));
	}
	for case in vectors["crc32c"].as_array().expect("crc") {
		let input = unhex(case["input_hex"].as_str().expect("input"));
		assert_eq!(u64::from(crc32c::crc32c(&input)), case["crc"].as_u64().expect("crc"));
	}
}
